services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`schmaglowski.de`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"

networks:
  traefik:
    external: true
  default: